//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmallBusiness
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class smallbusinessEntities : DbContext
    {
        public smallbusinessEntities()
            : base("name=smallbusinessEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<producttable> producttable { get; set; }
        public virtual DbSet<users> users { get; set; }
        public virtual DbSet<warehouse> warehouse { get; set; }
        public virtual DbSet<tasks> tasks { get; set; }
        public virtual DbSet<tasks_view> tasks_view { get; set; }
        public virtual DbSet<warehouse_operations> warehouse_operations { get; set; }
        public virtual DbSet<warehouse_ops_view> warehouse_ops_view { get; set; }
        public virtual DbSet<warehouse_view> warehouse_view { get; set; }
    }
}
