//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmallBusiness
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductView
    {
        public double Price { get; set; }
        public int id { get; set; }
        public string Name { get; set; }
        public string Article { get; set; }
        public string Manufacturer { get; set; }
        public string Description { get; set; }
    }
}
