//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmallBusiness
{
    using System;
    using System.Collections.Generic;
    
    public partial class tasks
    {
        public int id { get; set; }
        public string TaskText { get; set; }
        public string TaskTheme { get; set; }
        public int ToUser { get; set; }
    
        public virtual users users { get; set; }
    }
}
