//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmallBusiness
{
    using System;
    using System.Collections.Generic;
    
    public partial class warehouse
    {
        public int id { get; set; }
        public int id_product { get; set; }
        public int Quantity { get; set; }
        public float Packing { get; set; }
        public string Type { get; set; }
    
        public virtual producttable producttable { get; set; }
    }
}
